# Generated by Django 5.1.6 on 2025-02-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_create_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
