# Generated by Django 5.1.6 on 2025-02-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_image_latitude_image_location_name_image_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
